config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root to: 'blogs#index'
  get 'favorites/create'

  get 'favorites/destroy'

  get 'sessions/new'
  resources :contacts
  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :favorites, only: %i[create destroy]
  # resources :blogs
  resources :blogs, only: %i[index new show create edit update destroy] do
    collection do
      get :confirm
      post :check
    end
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length:{minimum: 1, maximum: 25}
  validates :content, presence: true, length:{minimum: 1, maximum: 140}
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :login_validate, only: %i[new edit show]
  before_action :set_blog, only: %i[edit show update destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order(updated_at: :desc)
    render layout: 'index.html.erb'
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  # GET /blogs/new
  def new
    if params[:back]
     @blog = Blog.new(blog_params)
     else
     @blog = Blog.new
    end
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.image.retrieve_from_cache! params[:cache][:image]
    @blog.user_id = current_user.id # 現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    #キャッシュから画像を復元する
    BlogtoMailer.blogto_mail(@blog.user).deliver
    # 省略

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    # @favorites_blogs= Blog.where(user_id: current_user.favorites)
    @favorites_blogs = current_user.favorite_blogs
    render layout: 'index.html.erb'
  end

  def check
    #@blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title,:content,:image)
  end

  def login_validate
    #  if !logged_in?
    #     redirect_to new_session_path
    if session[:user_id]
      begin
        @user = User.find(session[:user_id])
      rescue ActiveRecord::RecordNotFound
        reset_session
      end
    end
    redirect_to new_session_path unless @user
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'check'
      check_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, :html => {multipart: true} ,url: choose_new_or_edit ) do |form| %>
<% if @blog.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@blog.errors.count, "個エラーがあります,") %>保存されていません。</h2>

  <ul>
    <% @blog.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">
  <%= form.label :title %>
  <%= form.text_field :title,class: "form-control"%>
  <%#= form.hidden_field :id %>
</div>

<div class="field form-group">
  <%= form.label :content %><br>
  <%= form.text_area :content, id: :blog_content ,size: "40x4",class: "form-control"%>

</div>

<div class="field form-group">
  <%= form.label :image %>
  <%= form.file_field :image ,class: "form-control"%>

</div>

<%= form.submit  class: "btn btn-primary" %><%= link_to '戻る', blogs_path,class: "btn btn-primary"%>

<% end %>
<!-- カリキュラム23 -->

app/views/blogs/check.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <!-- ここ追加 -->
 <%= hidden_field_tag :"cache[image]", @blog.image.cache_name %>
  <p>タイトル:<%= @blog.title %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/confirm.html.erb
<h1>お気に入り一覧</h1>
<%= link_to '戻る', blogs_path %>
<table>
  <thead>
    <tr>
      <!-- <th>Title</th> -->
      <th></th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% @favorites_blogs.each do |blog| %>
      <tr class="wrapper">
        <td id="blogscontent"><%= image_tag blog.image ,size:'300x200'%></td>
        <td id="blogscontent"><%= blog.title %></td>
        <td id="blogscontent"><%= blog.content %></td>
        <td id="blogpr"><br><br><br><br><%= blog.user.name %></td>
        <td id="blogpr"><br><br><br><br><%= link_to 'お気に入り解除する', favorite_path(blog.id), method: :delete, class: 'btn btn-xs btn-danger'%></td>
        <td id="blogpr"><br><br><br><br><%= blog.updated_at %></td>

      </tr>

    <% end %>
</tbody>
</table>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>
<% if @blog.user == current_user %>
<%= link_to '確認', @blog , class: "btn btn-xs btn-primary" %>|
<% end %>
<%= link_to '戻る', blogs_path  , class: "btn btn-xs btn-primary"%>

app/views/blogs/index.html.erb
<h1>Blogs</h1>
<%= link_to '新しいBlos', new_blog_path %>
<table>
  <thead>
    <tr>
      <!-- <th>Title</th> -->
      <th></th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr class="wrapper">
        <td id="blogscontent"><%= image_tag blog.image_url,width:350 %></td>
        <td id="blogscontent"><%= blog.title %></td>
        <td id="blogscontent"><%= blog.content %></td>
        <td class="adjust"><br><br><br><br><%= link_to '確認', blog, class: "btn btn-xs btn-primary" %></td>

        <% if blog.user == current_user %>
        <td class="adjust"><br><br><br><br><%= link_to '編集', edit_blog_path(blog), class: "btn btn-xs btn-primary" %></td>
        <td class="adjust"><br><br><br><br><%= link_to '削除', blog, class: "btn btn-xs btn-warning",method: :delete, data: { confirm: '削除して構いませんか？' } %></td>
        <% end %>
        <td id="blogpr"><br><br><br><br><%= blog.user.name %></td>
        <td id="blogpr"><br><br><br><br><%= blog.updated_at %></td>
      </tr>
    <% end %>
</tbody>
</table>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>
<% if @blog.user_id == current_user %>
<%= link_to '編集', edit_blog_path(@blog)  , class: "btn btn-xs btn-primary"%> |

<%end%>
<%= link_to '戻る', blogs_path , class: "btn btn-xs btn-primary" %>

<% unless @blog.user == current_user %>

  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-xs btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-xs,btn-prymary' %>
  <% end %>
<% end %>