config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root to: 'blogs#index'
  get 'favorites/create'

  get 'favorites/destroy'

  get 'sessions/new'
  resources :contacts
  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :favorites, only: %i[create destroy]
  # resources :blogs
  resources :blogs, only: %i[index new show create edit update destroy] do
    collection do
      get :confirm
      post :check
    end
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_aside1.html.erb
        <aside class=" hidden-xs col-md-3 col-lg-3 maincontents1">
          <article class="">
            <h2>ここにイメージ画像を入れる</h2>
            <ul class="">
              <li>ダミー</li>
              <li>ダミー</li>
              <li>ダミー</li>
              <li>ダミー</li>
              <li>ダミー</li>
            </ul>
          </article>
        </aside>

app/views/layouts/_aside2.html.erb
<aside class="hidden-xs col-md-3 col-lg-3 maincontents3">
  <article class="">
    <h1>New Feed</h1>
    <%= image_tag current_user.proimage %>
    <%= form_with(model: current_user, local: true) do |form| %>
      <% if current_user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(current_user.errors.count, "個エラーがあります,") %>保存されていません。</h2>

          <ul>
          <% current_user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <div class="field">
    <%= form.label :proimage %>
    <%= form.file_field :proimage %>
    <%= form.hidden_field :id %>
    </div>

    <div class="actions">
      <%= form.submit '保存する' %>
    </div>
    <% end %>
  </article>
</aside>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <nav id="nav" class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
        <li><%= link_to "お気に入り一覧へ", confirm_blogs_path %></li>
        <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
      <% else %>
        <li><%= link_to "サインアップ", new_user_path %></li>
        <li><%= link_to "ログイン", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%=render 'layouts/header'%>
      <!-- <div class="jumbotron"></div> -->
      <div class="row">

        <%= render 'layouts/aside1' %>

        <div class="col-xs-12 col-md-6 col-lg-6 text-center maincontents2">
          <%= yield %>
        </div>
        <% if logged_in? %>
        <%= render 'layouts/aside2' %>
        <% end %>
        <footer class="footer">
          <div class="container">
            <p class="text-muted">Place sticky footer content here.</p>
          </div>
        </footer>
      </div>
    </div>
          <!-- flashにメッセージがある時 -->
    <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('danger','error').gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
    <% end %>
  </body>
</html>

app/views/layouts/contact_mail.html.erb
<h1>お問い合わせが完了しました！</h1>

<h4>name: <%= @contact.name %></h4>

<h4>お問い合わせ内容の確認</h4>

<p>content: <%= @contact.content %></p>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%=render 'layouts/header'%>
      <!-- <div class="jumbotron">ここに写真が来る</div> -->
      <div class="jumbotron">
        <h1>TwittercloneをBootstrapで実装</h1>
      </div>
      <div class="row">

        <%= render 'layouts/aside1'%>
        <div class="col-xs-12 col-md-6 col-lg-6 text-center maincontents2">
          <%= yield %>
        </div>
        <% if logged_in? %>
        <%= render 'layouts/aside2'%>
        <% end %>
        <footer class="footer">
          <div class="container">
            <p class="text-muted">Place sticky footer content here.</p>
          </div>
        </footer>
      </div>
    </div>
    <!-- flashにメッセージがある時 -->
    <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
    <% end %>
  </body>
</html>